services:
  - type: web
    name: docx-to-pdf-api
    env: python
    buildCommand: |
      apt-get update && apt-get install -y libreoffice
      pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
